# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'ClientDemoDevOps3ServiceConnection'
    subscriptionId: '0f1a8fff-4fff-43e8-b54c-e63ac7bda305'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'clientdemodevops2-rg'
    location: 'East US'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/saabdal/azure-quickstart-templates/master/101-synapse-poc/azuredeploy.json'
    csmParametersFileLink: 'https://raw.githubusercontent.com/saabdal/azure-quickstart-templates/master/101-synapse-poc/azuredeploy.parameters.json'
    deploymentMode: 'Incremental'
    deploymentName: 'synapsepocdeployment'